//Model that is interacting with our database to create.
const mongoose = require('mongoose')
//Blueprint for objects to be built.
//Three key value pairs are being created here but also mongoose is generating a fourth id for the object itself seen in mongodb.

const TodoSchema = new mongoose.Schema({
  todo: {
    type: String,
    required: true,
  },
  completed: {
    type: Boolean,
    required: true,
  },
  userId: {
    type: String,
    required: true
  }
})

//This is declaring our document/object name as 'Todo' and schema name as TodoSchema
//If we wanted to name our collection to something than the auto generated plura of our objecct name Todos, we can add a third parameter.
//Ex module.exports = mongoose.model('Todo', TodoSchema, 'Unicorn') would create a collection in our mongodb called Unicorn instead of Todos
//If we wanted to name the database itself in collections we would have to add the name to our connection string in our .env file.
//Ex: mongodb+srv://user:wegoget@password.lcw3nyl.mongodb.net/Chicken?retryWrites=true&w=majority would change our autogenerated database name to Chicken.
module.exports = mongoose.model('Todo', TodoSchema)
